accounts/urls.py
from django.urls import path

from . import views

app_name="accounts"

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
]

buat_jadwal/urls.py
from django.urls import path
from . import views

app_name = 'buat_jadwal'

urlpatterns = [
    path('', views.buat, name='buat'),
    path('berhasil', views.berhasil, name='berhasil'),
    path('list', views.list_jadwal, name='list'),
]

carijadwal/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'carijadwal'

urlpatterns = [
        # url(r'^add/(?P<add_id>[0-9]+)$', views.add, name='add'),
        # url(r'^delete/(?P<delete_id>[0-9]+)$', views.delete, name='delete'),
        # url(r'^$', HomePageView.as_view(), name='home'),
        # url(r'^search/$', SearchResultsView.as_view(), name='search_results'),
        path('add/<int:add_id>', views.add, name="add"),
        path('', views.HomePageView.as_view(), name="home"),
        path('lihatjadwal', views.lihatjadwal, name="lihatjadwal"),
        path('search/', views.SearchResultsView.as_view(), name="search_results"),

]

tutorq/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.views.generic.base import TemplateView 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('template', views.template),
    
    # for account
    path('accounts/', include('accounts.urls')), 
    path('accounts/', include('django.contrib.auth.urls')), 
    path('', TemplateView.as_view(template_name='accounts/home.html'), name='home'), # new
    path('buatJadwal/', include('buat_jadwal.urls')),
    path('cariJadwal/', include('carijadwal.urls')),
    path('', views.home, name='homepage'),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class CustomUser(AbstractUser):
    skills = models.CharField(max_length=50)
    


    #def __str__(self):
    #    return self.email

buat_jadwal/models.py
from django.contrib.auth import get_user_model
from django.db import models

# Create your models here.
class Jadwal(models.Model):
    '''
    This is a model for Jadwal
    '''
    HARI = [
        ('SENIN', 'Senin'),
        ('SELASA', 'Selasa'),
        ('RABU', 'Rabu'),
        ('KAMIS', 'Kamis'),
        ('JUMAT', 'Jumat'),
        ('SABTU', 'Sabtu'),
        ('MINGGU', 'Minggu')
    ]

    tutor = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
        null=True,
        blank=True
    )

    matkul = models.CharField(
        max_length=20
    )

    hari = models.CharField(
        max_length=6,
        choices=HARI,
    )

    jam_mulai = models.TimeField()

    jam_selesai = models.TimeField()

carijadwal/models.py
from django.db import models
from django.contrib.auth import get_user_model
from buat_jadwal.models import Jadwal
# Create your models here.


class RelasiJadwal(models.Model):

    tutee = models.ForeignKey(
	    get_user_model(),
	    on_delete=models.CASCADE,
	    null=True,
	    blank=True,
        )
    
    jadwal = models.ForeignKey(
	    Jadwal,
	    on_delete=models.CASCADE,
	    null=True,
	    blank=True,
        )

	

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = CustomUser
        fields = ('username', 'skills')

buat_jadwal/forms.py
from django import forms
from .models import Jadwal

class BuatJadwalForms(forms.ModelForm):
    class Meta:
        model = Jadwal
        fields = ['hari', 'matkul', 'jam_mulai', 'jam_selesai']
        widgets = {
            'hari': forms.Select(
            ),
            'jam_mulai': forms.TimeInput(
                attrs={
                    'type':'time'
                }
            ),
            'jam_selesai': forms.TimeInput(
                attrs={
                    'type':'time'
                }
            ),
            'is_hidden':False
        }
    

carijadwal/forms.py
from django import forms

class SearchForm(forms.ModelForm):
	class Meta:
		matkul = forms.CharField(max_length=50)
		hari = forms.CharField(max_length=50)

accounts/views.py
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView

from .forms import CustomUserCreationForm

class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'accounts/signup.html'

buat_jadwal/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from .forms import BuatJadwalForms
from .models import Jadwal

# Create your views here.
# @login_required
# @tutor_required
def buat(request):
    if request.method == 'POST':
        form = BuatJadwalForms(request.POST)
        form.tutor = request.user
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('homepage'))
    else:
        form = BuatJadwalForms()
    return render(
        request,
        'buat_jadwal/buat_jadwal.html',
        {
            'form': form,
        }
    )

def berhasil(request):
    return render(request, 'buat_jadwal/berhasil.html')

def list_jadwal(request):
    jadwals = Jadwal.objects.order_by('hari')
    return render(request, 'buat_jadwal/list.html', {
        'jadwals': jadwals
    })

carijadwal/views.py
from django.shortcuts import render, redirect
from .models import RelasiJadwal
from .forms import SearchForm
from django.views.generic import TemplateView, ListView
from django.db.models import Q
from buat_jadwal.models import Jadwal


def add(request, add_id):
        tutee_add = request.user;
        jadwal_add = Jadwal.objects.get(id=add_id)

        relasi = RelasiJadwal(tutee=tutee_add, jadwal=jadwal_add)
        relasi.save()
                
        #jadwal_form = JadwalForm(request.POST or None, initial=ubah, instance=jadwal_change)
        #jadwal_form.save()

        return render(request, 'carijadwal/home.html')
def delete(request, delete_id):
        pass

        #return render(request, 'home.html')

def lihatjadwal(request):
        model = Jadwal
        template_name = 'carijadwal/list.html'
        relasi_relasi = RelasiJadwal.objects.filter(tutee=request.user)
        object_list = []

        for relasi in relasi_relasi:
            r = Jadwal.objects.get(pk=relasi.jadwal.id)
            if(r not in object_list): object_list.append(r)
        
        context = {'object_list': object_list}
        return render(request, template_name, context)
        

# def home(request):
#     if request.method == 'POST':
#         form = ContactForm(request.POST)
#         if form.is_valid():
#             pass  # does nothing, just trigger the validation
#     else:
#         form = ContactForm()
#     return render(request, 'search.html', {'form': form})

class HomePageView(TemplateView):
    template_name = 'carijadwal/home.html'

class SearchResultsView(ListView):
    model = Jadwal
    template_name = 'carijadwal/search_results.html'

    def get_queryset(self):
        query1 = self.request.GET.get('q1')
        query2 = self.request.GET.get('q2')
        object_list = Jadwal.objects.filter(
            Q(matkul__icontains=query1) & Q(hari__icontains=query2)
        )
        return object_list

tutorq/views.py
from django.shortcuts import render

def hello(request):
    return render(request, 'hello_world.html')

def template(request):
    return render(request, 'template.html')

def home(request):
    return render(request, 'accounts/home.html')

accounts/templates/accounts/home.html
{% extends 'template.html' %}

{% block title %}Home{% endblock %}

{% block views %}
{% load static %}
{% if user.is_authenticated %}
  <p>Hi {{ user.username }}!
  {% if user.skills %}
  <p>Tutor {{ user.skills }}!</p>
  {% else %} Tutee!
  {% endif %}
  <p><a href="{% url 'logout' %}">logout</a></p>
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">login tutor</a>
  <p>Don't have an account yet?</p>
  <a href="{% url 'login' %}/../../signup">signup tutor</a>
{% endif %}
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'template.html' %}
{% load static %}

{% block title %}Sign Up{% endblock %}

{% block views %}

<h2>Sign up</h2>
<form method="post">
  {% csrf_token %}
  {% for fields in form %}
    {{ fields.errors }}
    <div>
      {{ fields.label_tag }} <br> {{ fields }}
    </div>
  {% endfor %}
  <button type="submit">Sign up</button>
</form>
{% endblock %}

buat_jadwal/templates/buat_jadwal/berhasil.html
{% extends 'template.html' %}

{% block views %}
  <h1>Berhasil</h1>
{% endblock views %}

buat_jadwal/templates/buat_jadwal/buat_jadwal.html
{% extends 'base.html' %}

{% block content %}
{% if invalid_user %}
  <h1>You haven't log in yet</h1>
{% endif %}
<form method='POST' action='{% url 'buat_jadwal:buat' %}'>
  {% csrf_token %}
  {% for fields in form %}
      <div>
      {{ fields.errors }}
      </div>
      <div style="margin: 5px">
      {{ fields.label_tag }}<br>
      {{ fields }}
      </div>
    {% endfor %}
    <input class='submit-button' type='submit'>
</form>
{% endblock content %}

buat_jadwal/templates/buat_jadwal/list.html
{% extends 'base.html' %}

{% block content %}
  {% for jadwal in jadwals %}
    <p>{{ jadwal.hari }}</p>
    <p>{{ jadwal.jam_mulai }}</p>
    <p>{{ jadwal.jam_selesai }}</p>
  {% endfor %}
{% endblock content %}

carijadwal/templates/carijadwal/home.html
{% extends "template.html"%}

{% block views %}
<h1 style="text-align:center; padding:5%;"> Cari Jadwal </h1>
<form action="{% url 'carijadwal:search_results' %}" method="get">
	<!-- Search form -->
	<div class="active-purple-3 active-purple-4 mb-4">
	  <input name = "q1" class="form-control" type="text" placeholder="Cari jadwal berdasarkan matkul" aria-label="Search">
	</div>
	<!-- Search form -->
	<div class="active-cyan-3 active-cyan-4 mb-4">
	  <input name = "q2" class="form-control" type="text" placeholder="Cari jadwal berdasarkan hari" aria-label="Search">
	</div>
	<button type="submit" class="btn btn-primary">Cari jadwal</button>
</form>
<div>
{% endblock views %}

carijadwal/templates/carijadwal/list.html
{% extends "template.html"%}

{% block views %}
	<h1 style="text-align:center; padding:5%;"> Lihat Jadwal </h1>
		  	<table class="table">
		  <thead>
		    <tr>
		      <th scope="col">#</th>
		      <th scope="col">Matkul</th>
		      <th scope="col">Hari</th>
		      <th scope="col">Jam Mulai</th>
		      <th scope="col">Jam Selesai</th>
		    </tr>
		  </thead>
		  <tbody>
		  	{% for jadwal in object_list%}
			    <tr>
			      <th scope="row">{{forloop.counter}}</th>
				  <td>{{jadwal.matkul}}</td>
				  <td>{{jadwal.hari}}</td>
				  <td>{{jadwal.jam_mulai}}</td>
				  <td>{{jadwal.jam_selesai}}</td>
				 
			    </tr>
		    {% endfor %}

  </tbody>
{% endblock views %}

carijadwal/templates/carijadwal/search_results.html
{% extends "template.html"%}

{% block views %}
	<h1 style="text-align:center; padding:5%;"> Hasil Pencarian </h1>

		  	<table class="table">
		  <thead>
		    <tr>
		      <th scope="col">#</th>
		      <th scope="col">Matkul</th>
		      <th scope="col">Hari</th>
		      <th scope="col">Jam Mulai</th>
		      <th scope="col">Jam Selesai</th>
			  <th scope="col">Menambahkan Jadwal</th>
		    </tr>
		  </thead>
		  <tbody>
		  	{% for jadwal in object_list%}
			    <tr>
			      <th scope="row">{{forloop.counter}}</th>
				  <td>{{jadwal.matkul}}</td>
				  <td>{{jadwal.hari}}</td>
				  <td>{{jadwal.jam_mulai}}</td>
				  <td>{{jadwal.jam_selesai}}</td>
				  <td> <a class="btn btn-primary" href="{% url 'carijadwal:add' jadwal.id%}"> Tambahkan </a>
			    </tr>
		    {% endfor %}

  </tbody>
{% endblock views %}

tutorq/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>{{ title }}</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js" integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o" crossorigin="anonymous"></script>
    {% block style %}
    {% endblock style %}

  </head>

  <body>
    <div class="container">
        {% block content %}

        {% endblock content %}

    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

tutorq/templates/hello_world.html
<!DOCTYPE>
<html>
  <head>
    <title>HELLO WORLD</title>
  </head>
  <body>
    <h1>Hello World</h1>
  </body>
</html>

tutorq/templates/template.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
  <link href="{% static 'css/template.css' %}" type='text/css' rel='stylesheet'>
  {% block specific_style %}
  {% endblock specific_style %}
{% endblock style %}

{% block content %}
  <nav class="navbar navbar-default">
    <div class="navbar header">
      <img src="{% static 'image 2.png' %}">
    </div>
    <div class="container-fluid">
      <ul class="nav navbar-nav" style="flex-direction: row">
        <li><a href="{% url 'accounts:signup' %}">Sign Up</a></li>
        <li><a href="{% url 'login' %}">Log in</a></li>
        <li><a href="{% url 'carijadwal:home' %}">Cari Jadwal</a></li>
        <li><a href="{% url 'carijadwal:lihatjadwal' %}">Lihat Jadwal</a></li>
        <li><a href="{% url 'buat_jadwal:buat' %}">Buat Jadwal</a></li>
      </ul>
    </div>
  </nav>
  {% block views %}
  {% endblock views %}
{% endblock content %}